### ISSUE TITLE
Не работает у всех игроков

### ISSUE THREAD

**Issue by XionioXMaster** [MeidoNoHitsuji/DiscordAuthSystem_module#2]
Во время успешной авторизации лаунчер намертво висит, я использовал версию гравита под которую писался модуль но это не решило проблему
![image](https://user-images.githubusercontent.com/86433158/183311254-d7a57fee-2726-472f-bd4b-e2d15a096c47.png)
![image](https://user-images.githubusercontent.com/86433158/183311256-6108d196-99e7-4dc5-a7db-3891cf3fd1a8.png)
![image](https://user-images.githubusercontent.com/86433158/183311258-61924423-59b4-4b4d-a56d-43def86b54ec.png)
![image](https://user-images.githubusercontent.com/86433158/183311259-16c04f41-6b35-4ad1-94ad-ac8cd91bf185.png)

Лог лаунчера https://pastebin.com/bSHB0Tea Ошибок не поступает

Есть предположение что где-то ошибка в рантайме, в любом случае у меня и ещё в нескольких человек всё работает отлично

Тестировалось на 11,10, 7 виндовс

Вот запуск клиента который не может войти, **да там есть несколько Java но их мы сносили что бы узнать в чём проблема, проблема решена не была.**

C:\Users\Александр\Desktop>java -Dlauncher.debug=true -Dlauncher.stacktrace=true -Dlauncher.dev=true -jar MIA.exe
GravitLauncher (fork sashok724's Launcher) Launcher v5.2.13-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
2022.08.07 22:36:11 [DEBUG] Testing stacktrace
2022.08.07 22:36:11 [DEBUG] Verifying class loader
2022.08.07 22:36:11 [DEBUG] Verifying JVM architecture
2022.08.07 22:36:11 [INFO] Launcher for project Made In Abyss Private install
2022.08.07 22:36:11 [INFO] If need debug output use -Dlauncher.debug=true
2022.08.07 22:36:11 [INFO] If need stacktrace output use -Dlauncher.stacktrace=true
2022.08.07 22:36:11 [INFO] Restart Launcher with JavaAgent...
2022.08.07 22:36:11 [DEBUG] Found Java 8 b321 in C:\Program Files\Java\jre1.8.0_281 javafx supported
2022.08.07 22:36:11 [DEBUG] Found Java 9 b0 in C:\Program Files (x86)\Common Files\Oracle\Java javafx not supported
2022.08.07 22:36:11 [DEBUG] Found Java 8 b312 in C:\Program Files\Java\jdk8u312-b07-jre javafx not supported
2022.08.07 22:36:11 [DEBUG] Commandline: [C:\Program Files\Java\jre1.8.0_281\bin\java.exe, -Djdk.attach.allowAttachSelf, -XX:+DisableAttachMechanism, -Dlauncher.stacktrace=true, -Dlauncher.dev=true, -Dlauncher.debug=true, -Xmx256M, -cp, C:\Users\Александр\Desktop\MIA.exe, pro.gravit.launcher.MIAKYeA45eRwGh]
2022.08.07 22:36:11 [DEBUG] Testing stacktrace
2022.08.07 22:36:11 [DEBUG] Verifying class loader
2022.08.07 22:36:11 [DEBUG] Verifying JVM architecture
GravitLauncher (fork sashok724's Launcher) Launcher v5.2.13-1 stable
License for Launcher GPLv3. SourceCode: https://github.com/GravitLauncher/Launcher
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022.08.07 22:36:12 [WARN] JLine2 isn't in classpath, using std
2022.08.07 22:36:12 [DEBUG] Start async connection to ws://204.10.194.61:25569/api
2022.08.07 22:36:13 [INFO] Reading EC keypair
2022.08.07 22:36:13 [DEBUG] Initialized Discord Game. Application ID 858689818417692693
2022.08.07 22:36:13 [DEBUG] Dir: C:\Users\Александр\AppData\Roaming\Made In Abyss Private install
2022.08.07 22:36:13 [DEBUG] Start JavaFX Application
2022.08.07 22:36:13 [DEBUG] In-Launcher Java Version found: Java 17b777 x64 javafx false
2022.08.07 22:36:13 [INFO] Java pkgs: null
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 8.0.321
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 8.0.321
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 8.0.321
2022.08.07 22:36:15 [DEBUG] Fxml load overlay/webauth/webauth.fxml time: c: 3 | l: 130 | total: 133
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/login/logintotp.fxml time: c: 2 | l: 132 | total: 134Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 18 by JavaFX runtime of version 8.0.321

2022.08.07 22:36:15 [DEBUG] Fxml load scenes/login/loginpassword.fxml time: c: 4 | l: 136 | total: 140
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/login/login.fxml time: c: 7 | l: 137 | total: 144
2022.08.07 22:36:15 [DEBUG] Fxml load overlay/processing/processing.fxml time: c: 0 | l: 5 | total: 5
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/login/loginonly.fxml time: c: 0 | l: 11 | total: 11
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.321
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.321
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/options/options.fxml time: c: 0 | l: 87 | total: 87
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/servermenu/servermenu.fxml time: c: 0 | l: 97 | total: 97
Aug 07, 2022 10:36:15 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.321
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/serverinfo/serverinfo.fxml time: c: 0 | l: 102 | total: 102
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/console/console.fxml time: c: 1 | l: 23 | total: 24
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/update/update.fxml time: c: 0 | l: 16 | total: 16
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/settings/settings.fxml time: c: 0 | l: 109 | total: 109
2022.08.07 22:36:15 [DEBUG] Fxml load scenes/debug/debug.fxml time: c: 0 | l: 16 | total: 16
2022.08.07 22:36:15 [DEBUG] Scene login disabled (1)
2022.08.07 22:36:15 [DEV] Send: {"requestUUID":"ae214d6c-695c-48ee-b274-2d1df126a4f6","type":"getAvailabilityAuth"}
2022.08.07 22:36:15 [DEV] RequestFuture complete normally
2022.08.07 22:36:15 [DEV] Processing event getAvailabilityAuth
2022.08.07 22:36:15 [DEV] Message: {"list":[{"details":[{"url":"https://discord.com/oauth2/authorize?response_type\u003dcode\u0026client_id\u003d858689818417692693\u0026scope\u003didentify%20guilds%20guilds.members.read%20email\u0026state\u003dba484071-1b52-4665-b1d1-108c40b14f8a\u0026redirect_uri\u003dhttp://204.10.194.61:25569/webapi/auth/discord\u0026prompt\u003dconsent","redirectUrl":"http://204.10.194.61:25569/webapi/auth/discord","canBrowser":true,"onlyBrowser":true,"type":"webview"}],"name":"std","displayName":"Default"}],"features":1,"requestUUID":"ae214d6c-695c-48ee-b274-2d1df126a4f6","type":"getAvailabilityAuth"}
2022.08.07 22:36:15 [INFO] Selected auth: std
2022.08.07 22:36:15 [INFO] Added std: Default
2022.08.07 22:36:15 [DEV] Send: {"secureHash":"mso37xT2zdWyLDA+C+dWJHaqjx6Tm8TUHWEiUHZoSEI\u003d","secureSalt":"b1b4feda76d9aa049ef861776f1d9118","digest":"ajasLOd0b1CX7rLDLfQ_ighbP8-If58xE8w68ZRh8AphuBKQ1wPMEvQRFpB9EDFMbyv_wWaVOx-z6IL0OcPL2A\u003d\u003d","launcher_type":2,"requestUUID":"8f31b2fb-f883-4fb8-8d74-ea6d0e1c5faf","type":"launcher"}
2022.08.07 22:36:15 [DEV] RequestFuture complete normally
2022.08.07 22:36:15 [DEV] Launcher update processed
2022.08.07 22:36:15 [DEV] Processing event launcher
2022.08.07 22:36:15 [DEV] Message: {"url":"http://204.10.194.61:25569/MIA.exe","needUpdate":false,"launcherExtendedToken":"eyJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJMYXVuY2hTZXJ2ZXIiLCJjaGVja1NpZ24iOnRydWUsImV4cCI6MTY1OTkyOTc3NH0.DYGuYmNHhGG-u_lxIdMm8y4AxCbrGmR6oGm5KQ212U4rQnK0LjxTpCMi5sgXe5m_kXQqGjOKuspKmY7rAb2pgA","requestUUID":"8f31b2fb-f883-4fb8-8d74-ea6d0e1c5faf","type":"launcher"}
2022.08.07 22:36:15 [DEBUG] Scene login enabled (0)
2022.08.07 22:36:21 [DEBUG] Scene login disabled (1)
2022.08.07 22:36:21 [DEBUG] Scene login enabled (0)
2022.08.07 22:37:21 [DEV] Processing event auth
2022.08.07 22:37:34 [DEV] Receive auth event. Send next scene true
2022.08.07 22:37:34 [DEBUG] X: 22.000000, Y: 134.000000
2022.08.07 22:37:34 [DEBUG] Scene login disabled (1)
2022.08.07 22:37:34 [DEV] Send: {"requestUUID":"04666724-25cc-454b-b0b8-fdd31a34af5d","type":"profiles"}
2022.08.07 22:37:34 [DEV] Message: {"permissions":{},"playerProfile":{"uuid":"58d89780-10c3-4bfd-bc3f-bd62f45e4970","username":"fromkai","assets":{},"properties":{}},"oauth":{"accessToken":"Jm6c0TQjEH8nXD2sKfLn6IzkGOKC3E","refreshToken":"Zj61UP5uebgnQALdzmyPNTsVdueWfS","expire":604800000000},"requestUUID":"fac0e2bd-9820-4449-b191-1d7c9bf781be","type":"auth"}

2022.08.07 22:37:46 [INFO] Command ''

2022.08.07 22:37:46 [INFO] Command ''

2022.08.07 22:37:47 [INFO] Command ''
зштп
2022.08.07 22:37:54 [INFO] Command '???'
2022.08.07 22:37:54 [ERROR] Unknown command: '???'
        at pro.gravit.utils.command.CommandHandler.lookup(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.eval(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.evalNative(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.eval(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.readLoop(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

ping
2022.08.07 22:38:02 [INFO] Command 'ping'
2022.08.07 22:38:02 [ERROR] Unknown command: 'ping'
        at pro.gravit.utils.command.CommandHandler.lookup(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.eval(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.evalNative(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.eval(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.readLoop(Unknown Source)
        at pro.gravit.utils.command.CommandHandler.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Завершить выполнение пакетного файла [Y(да)/N(нет)]?

C:\Users\Александр\Desktop>pause
^CException in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
        at javafx.scene.Scene.pick(Scene.java:1945)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
        at javafx.scene.Scene.pick(Scene.java:1945)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
        at javafx.scene.Scene.pick(Scene.java:1945)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
        at javafx.scene.Scene.pick(Scene.java:1945)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3902)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3488)
        at javafx.scene.Scene.pick(Scene.java:1945)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3714)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1205)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:171)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)2022.08.07 22:38:14 [ERROR] java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at pro.gravit.repackage.io.netty.buffer.PooledByteBuf.setBytes(Unknown Source)
        at pro.gravit.repackage.io.netty.buffer.AbstractByteBuf.writeBytes(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKey(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.processSelectedKeys(Unknown Source)
        at pro.gravit.repackage.io.netty.channel.nio.NioEventLoop.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
        at pro.gravit.repackage.io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2997)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2991)2022.08.07 22:38:14 [INFO] WebSocket client disconnect

Завершить выполнение пакетного файла [Y(да)/N(нет)]?

**Comment by XionioXMaster** [comment]
![image](https://user-images.githubusercontent.com/86433158/183311540-ad5f5cbe-c57b-4bcd-bc9a-2214bdf86ca5.png)
Есть моменты когда игрока авторизирует но не пускает к списку серверов
Лог проишествия https://pastebin.com/6n346a9n
